### ISSUE TITLE
Mettre en place un dashboard Metabase

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#106]
Mettre en place un Metabase en surcouche de Matomo => action à la main de Noemie de Selego, besoin de coordination avec Julien & Laurent

**Comment by LauraAMIRIFabrique** [comment]
Dashboard en cours de construction avec Noemie.
On a constaté ce jour qu'il y avait des remontées inattendues dans Metabase sur la comptabilisation des events customs.
Cf pieces jointes.
Pour discussion le 16/02 à 10H.

**Comment by LauraAMIRIFabrique** [comment]
![Image](https://user-images.githubusercontent.com/113974143/219101469-48a20128-d23e-476d-96e7-abaf999b41a7.png)



![Image](https://user-images.githubusercontent.com/113974143/219101675-d16a3254-38cc-4f4b-9423-42f119a37da6.jpeg)

**Comment by LauraAMIRIFabrique** [comment]
Hypothèse : 

- soit notre site "pre fetch" les pages et déclenche à tort l'évenement
- soit matomo sur le site fait un "batch" d'évènement (au lieu d'envoyer un par un), et n'envoie le batch que, par exemple, tous les 10 events, y compris les events de changement de page. Il se retrouve donc dès fois à envoyer des events custom depuis une page différente de leur source. A tester avec les autres events custom pour confirmer

**Comment by LauraAMIRIFabrique** [comment]
Action en cours entre Noemie / Laurent / Julien

**Comment by sutter** [comment]
@LauraAMIRIFabrique je pense avoir fixé le ticket, mais le soucis c'est qu'il n'est vérifiable qu'en prod. Impossible pour moi de savoir s'il fonctionne avant de passer sur cet environnement.

**Comment by LauraAMIRIFabrique** [comment]
Vérifier à l'ouverture sur le nouveau NDD que ça suivra

**Comment by LauraAMIRIFabrique** [comment]
Tout fonctionne en prod ! je cloture. Merci pour votre travail
