### ISSUE TITLE
Page Annuaire - Dynamiser toute la page pour permettre l'ajout du processus de référencement à l'annuaire

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#108]
**URL concernée :** https://maisondelautisme.fabrique.social.gouv.fr/annuaire

**J'observe ce qui ne va pas :**  
Certains visiteurs souhaitent être référencés sur notre annuaire, ou suggérer des contacts de confiance.

**Je demande ce que je souhaiterais :**  
Ajouter le message suivant sur la page "Annuaire" : 
Vous êtes un professionnel, une association, un organisme etc... qui souhaitez être référencé sur notre annuaire ? Rendez-vous à cette adresse pour savoir comment faire : https://annuaire.autismeinfoservice.fr/etre-reference-annuaire/

**Comment by Valentinedhont** [comment]
Hello Laurent, 

Pour la page Annuaire, peux-tu remettre le texte qu'il y avait sur cette page et simplement ajouter le message de Laura (ci-dessus) en dessous s'il te plait ? Merci beaucoup

**Comment by LauraAMIRIFabrique** [comment]
J'ai retrouvé le contenu : 

Vous cherchez des contacts de confiance ? Un établissement ou un organisme ? Des professionnels de santé ? Une association ?

Rendez-vous sur l'[annuaire d'Autisme Info Service](https://annuaire.autismeinfoservice.fr/)


Je le mets à jour sur strapi directement et je cloture le ticket :)
