### ISSUE TITLE
Dimensionner les iframe et les photos pour que leurs tailles s'adaptent de manière responsive

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#171]
**URL concernée :** tout le site

**J'observe ce qui ne va pas :**
Lorsqu'on ajoute un PDF ou une vidéo en iframe, la taille n'est pas adaptée à la ta taille de l'écran.
Le même phénomène se produit lorsqu'on intègre une image dans une page.

Exemple avec un test sur la page Maison de l'autisme - cf les deux premières questions "TEST- comment venir en métro" et "TEST comment me repérer au sein de la Maison de l'autisme" https://mda-preprod.dev.fabrique.social.gouv.fr/la-maison-de-l-autisme

**Je demande ce que je voudrais :**
Dimensionner les iframes et les photos pour que leurs tailles s'adaptent en responsive

Cf screenshot ci-dessous 

![Capture d’écran 2023-03-15 à 14 20 31](https://user-images.githubusercontent.com/113974143/225321145-8fa47d28-b6c0-4dd9-8ed9-c45e5039a3b6.png)
![Capture d’écran 2023-03-15 à 14 20 46](https://user-images.githubusercontent.com/113974143/225321154-028b1e5c-9d27-4fde-9789-cdde7946cbaf.png)
![Capture d’écran 2023-03-15 à 14 20 54](https://user-images.githubusercontent.com/113974143/225321170-c066ca76-8cd2-44cd-a66a-d1440f340dcd.png)
<img width="1185" alt="Capture d’écran 2023-03-15 à 11 23 09" src="https://user-images.githubusercontent.com/113974143/225321179-b31f3889-86a6-470a-b553-2f10cdf35653.png">
<img width="1188" alt="Capture d’écran 2023-03-15 à 11 23 16" src="https://user-images.githubusercontent.com/113974143/225321181-854ec68e-a1df-425e-a8de-ac1c70f53c22.png">
![Capture d’écran 2023-03-15 à 14 20 11](https://user-images.githubusercontent.com/113974143/225321182-17f56295-1899-48e2-9e75-08db110a5e83.png)
![Capture d’écran 2023-03-15 à 14 20 21](https://user-images.githubusercontent.com/113974143/225321183-76d23dea-af34-46a0-bb11-f8207c68591d.png)

**Comment by sutter** [comment]
Je vois d'ou viens le soucis, je prends.

**Comment by LauraAMIRIFabrique** [comment]
Ok merci c'est bon pour moi en recette. Je passe en done.
