### ISSUE TITLE
Implémentation du HPA sur le produit

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/mda#178]
# Contexte

Avant l'ouverture du site je souhaite que vous consommiez les fonctionnalités d'ajustement dynamique des ressources de la plateforme. L'objectif est d'éviter le plus possible la saturation ou la surréservations de ressources systèmes après l'ouverture du site.

# Périmétre

A appliquer sur :
- web
- strapi
- meilinsearch

# Démarche de résolution

Dans les paramétrage de kontinuous remplacer pour chaque composant:
 - Paramètre replicas par autoscale et mettre en place les valeurs min, max
 - Ajuster les valeurs CPU, RAM

# DOD

- [ ] Composant web avec autoscaling `on` et paramétrage OK
- [ ] Composant strapi avec autoscaling `on` et paramétrage OK
- [ ] Composant mailinsearch avec autoscaling `on` et paramétrage OK

**Comment by igorrenquin** [comment]
https://github.com/SocialGouv/mda/pull/180

**Comment by paulsouche** [comment]
Released in 1.7.0
