### ISSUE TITLE
Page Je donne mon Avis - Modifier l'apparence de l'accusé d'envoi du feedback

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#197]
**URL concernée :** https://maisondelautisme-recette.fabrique.social.gouv.fr/je-donne-mon-avis

**J'observe ce qui ne va pas :**
Lorsqu'on envoie un feedback via le formulaire, un accusé d'envoi du feedback s'affiche en rouge avec une croix, ce qui donne l'impression qu'il y a une erreur.
je ne l'avais pas remarqué jusqu'ici :( 

**Je demande ce que je souhaiterais :**
Utiliser le modèle de succès d'envoi disponible dans le DSFR pour indiquer en vert que le message a bien été envoyé et pas en rouge comme un message d'erreur https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/alerte

**Comment by paulsouche** [comment]
D'eployé en prod ce jour

**Comment by LauraAMIRIFabrique** [comment]
Yes opérationnel en prod merci !
