### ISSUE TITLE
Page de glossaire

### ISSUE THREAD

**Issue by sutter** [SocialGouv/mda#27]
- [x] Création du gabarit de page
- [x] Branchement aux élément de navigation
- [x] Intégrer le contenu en dur

**Comment by sutter** [comment]
@LauraAMIRIFabrique Pour le contenu de cette page je vois que le document sur le drive est vide c'est normal  ?
https://docs.google.com/document/d/1JXDo73VmrboGcZa5CXndn57FXYnfT7PsOI0_8g0JQq0/edit

**Comment by LauraAMIRIFabrique** [comment]
Plusieurs coquilles :
- 1ere ligne en dessous du titre : enlever "Glossaire fourni par la DIA."
- AAH : enlever le U à "UAllocation aux adultes handicapés."
- AEEH : remplacer par "Allocation d'éducation de l’enfant handicapé."
- Ajouter : 
RQTH : 
Reconnaissance de la qualité de travailleur handicapé.

**Comment by LauraAMIRIFabrique** [comment]
AEEH : remplacer par "Allocation d'éducation de l’enfant handicapé."

Coquille : enlever le deuxième point après handicapé
