### ISSUE TITLE
Corriger la duplication de sous-entrées dans le menu

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#272]
**URL concernée :** pages Menu dans Strapi (préprod et prod)

**J'observe ce qui ne va pas :** 
Lorsque je souhaite modifier ou ajouter une sous-entrée dans l'entrée "Mon parcours" du menu et que je clique sur save, cela duplique les sous-entrée parent ou aidant et Professionnel de santé.

**Je demande ce que je souhaiterais :**
Ne pas dupliquer les sous entrées lors du clic sur save
<img width="874" alt="Capture d’écran 2023-04-12 à 13 01 03" src="https://user-images.githubusercontent.com/113974143/231438475-6beff5ee-c3c6-42a7-81e0-b09cf8d4e578.png">

**Comment by paulsouche** [comment]
Fixé en base de données. Pardon de cet oubli
