### ISSUE TITLE
Page modèle de courrier

### ISSUE THREAD

**Issue by sutter** [SocialGouv/mda#28]
- [x] Création du gabarit de page
 - [x] Branchement aux élément de navigation
 - [x] Mise en place du contenu

**Comment by LauraAMIRIFabrique** [comment]
Tous les docs à afficher dans la banque de modèle sont ici : https://drive.google.com/drive/folders/1ME31sHrZp7hLha1JSCODnt1wc5tAQbm9

**Comment by sutter** [comment]
![Image](https://user-images.githubusercontent.com/709456/214581022-9e961418-7d87-49cd-ba02-e98e4e9d8d83.png)

@LauraAMIRIFabrique je pense qu'une petite phrase sous le titre serait la bienvenue.

**Comment by LauraAMIRIFabrique** [comment]
Oui tu as raison.
Est-ce que les docs sont ouvrables en open office du coup ? je vois .doc et .docx en extension de fichier

Voici la phrase chapô :

Plusieurs personnes concernées nous ont partagé le besoin d'accéder à des modèles de courrier, à utiliser et personnaliser en cas de besoin. Vous trouverez ci-dessous ces modèles. Si vous avez des suggestions de modèles à ajouter, dites-le nous grâce au formulaire "[Je donne mon avis](https://mda-preprod.dev.fabrique.social.gouv.fr/je-donne-mon-avis)"
