### ISSUE TITLE
 Corriger un mauvais routage vers la page Politique de confidentialité

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#289]
**URL concernée :** https://maisondelautisme.gouv.fr/politique-de-confidentialite

**J'observe ce qui ne va pas :**
Dans le footer, au clic sur la page PC, le renvoi se fait vers la page Plan du site.
J'ai vérifié dans Strapi, le contenu PC est bien présent, il n'y a pas de redirection manuelle vers la page Plan du site (cf screenshot).

**Je demande ce que je souhaiterais :** 
Corriger ce routage pour que la page Politique de confidentialité route bien vers le contenu Strapi dédié

<img width="1502" alt="Capture d’écran 2023-04-17 à 15 56 51" src="https://user-images.githubusercontent.com/113974143/232506497-85bb91dc-5946-444c-8180-c115232f963c.png">

**Comment by paulsouche** [comment]
Fix en cours de deploy en Préprod

**Comment by LauraAMIRIFabrique** [comment]
Ok en préprod, go prod !
