### ISSUE TITLE
Page annuaire

### ISSUE THREAD

**Issue by sutter** [SocialGouv/mda#29]
- [x] Création du gabarit de page
 - [x] Branchement aux élément de navigation
- [x] Ajout du contenu

**Comment by sutter** [comment]
@LauraAMIRIFabrique tu peux me mettre le contenu SVP

**Comment by LauraAMIRIFabrique** [comment]
Vous cherchez des contacts de confiance ? Un établissement ou un organisme ? Des professionnels de santé ? Une association ?

Rendez-vous sur l'[annuaire d'Autisme Info Service](https://annuaire.autismeinfoservice.fr/)
