### ISSUE TITLE
Améliorer le SEO - bis

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#296]
**URL concernée :** toutes les pages

**J'observe ce qui ne va pas :**
Certains axes d'amélioration permettraient de gagner en qualité de référencement sur les moteurs de recherche

**Je demande ce que je souhaiterais :**
1/ l'open graph et les keywords
- Titre:  La Maison de l'autisme | maisondelautisme.gouv.fr
- Description : Aider les personnes concernées par l'autisme à trouver leurs réponses et à mener à bien leurs démarches.
- Image : en PJ 
- Keywords : autisme, troubles du spectre de l'autisme, TSA, TND, Troubles du neurodéveloppement, diagnostic, TDA/H, asperger, trouble autistique 

2/ cf email google console : 
- Google n'a pas pu identifier la vidéo proéminente sur la page
- Aucune URL de vignette fournie

3/ idealement https://maisondelautisme.gouv.fr/healthz ne devrait pas être dans le sitemap, ce n'est pas une url à faire apparaitre dans les résultat de recherche google

![maison-de-lautisme](https://user-images.githubusercontent.com/113974143/232784005-95c35690-fb4f-4a35-94e7-e52f2f2f5e97.png)

**Comment by LauraAMIRIFabrique** [comment]
1/ l'open graph et les keywords ==> done 

2/ cf email google console : 
Google n'a pas pu identifier la vidéo proéminente sur la page
Aucune URL de vignette fournie

==> on ne peut rien faire, c'est dépendant du fait qu'on intègre une vidéo en iframe, ce qui n'est pas une bonne pratique de SEO car cela ne permet pas de générer une balise vidéo pour le SEO (la preuve avec cet exemple). 

3/ idealement https://maisondelautisme.gouv.fr/healthz ne devrait pas être dans le sitemap, ce n'est pas une url à faire apparaitre dans les résultat de recherche google

==> à faire

**Comment by paulsouche** [comment]
La page healthz a été retirée. A release en prod + vérifier si le site map se met à jour dans la console google search

**Comment by LauraAMIRIFabrique** [comment]
1/ page healtz => à pousser en prod 
2/ balises canonical => à pousser en prod
3/ noindex => quelques URL ont été à nouveau identifiées comme non indexées, les corrections ont été apportées en ce sens ; en revanche, l'option robot txt est à ré-envisager pour Strapi. => à pousser en prod

**Comment by LauraAMIRIFabrique** [comment]
Ces éléments ont été déployé ; à vérifier en prod
