### ISSUE TITLE
Page La maison de l'autisme

### ISSUE THREAD

**Issue by sutter** [SocialGouv/mda#30]
- [x] Création du gabarit de page - pour la bêta, on prend uniquement un gabarit type fiche pratique avec le modèle questions réponses. Pour l'instant, on a pas encore de quoi créer une page intermédiaire + des sous pages, comme designé en cible dans [les maquettes figma.](https://www.figma.com/proto/XIRsmNcamQXI2tvuThg1n8/Website?node-id=211%3A31844&scaling=scale-down&page-id=6%3A7539&starting-point-node-id=135%3A31219) 
 - [x] Branchement aux élément de navigation
-  [x] Ajout du contenu de la page en statique
 - [x] Pour le bouton "Me rendre à la Maison de l'autisme", ajouter un lien d'accès Google Maps avec l'adresse de la MDA : 10 rue Waldeck Rochet, 93300 Aubervilliers

**Comment by LauraAMIRIFabrique** [comment]
Les questions sont dans le bon ordre et le chapô est à jour. Le lien google maps fonctionne.

Cependant, les réponses n'ont pas été mises à jour et il manque une question.

Lien vers le google doc avec les textes qui font foi (les questions y sont classées dans le bon ordre et les réponses sont à jour) : [Maison de l'autisme physique](https://docs.google.com/document/d/1ZQ4tlLWmGFZbxdljKO9sO4H-CotEEOh7OgkjgKwJprI/edit)
