### ISSUE TITLE
Page mentions légales

### ISSUE THREAD

**Issue by sutter** [SocialGouv/mda#31]
- [x] Création du gabarit de page
 - [x] Branchement aux élément de navigation
 - [ ] Ajout du contenu

**Comment by sutter** [comment]
[27012023 - \[La_maison_de_l'autisme\] - Mentions légales.docx](https://github.com/SocialGouv/mda/files/10519338/27012023.-.La_maison_de_l.autisme.-.Mentions.legales.docx)

**Comment by LauraAMIRIFabrique** [comment]
Remplacer le texte par :
Accessibilité 

La conformité aux normes d’accessibilité numérique est un objectif prioritaire, nous tâchons de rendre ce site accessible à toutes et à tous. Un audit est en cours de planification afin de pouvoir mettre à jour le statut d'accessibilité en bas de page.

![Image](https://user-images.githubusercontent.com/113974143/215436423-f5ff3c8b-950c-484a-b12e-16ad6e6f4601.png)
