### ISSUE TITLE
Améliorer le SEO du site - ter

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#314]
**URL concernée :** toutes les pages

**J'observe ce qui ne va pas :**
Certains axes d'amélioration permettraient de gagner en qualité de référencement sur les moteurs de recherche. 

**Je demande ce que je souhaiterais :**
Le rapport fourni par Jonathan devrait nous aider à définir ces axes. Ticket à updater à sa réception.

<img width="1192" alt="Capture d’écran 2023-05-04 à 13 45 29" src="https://user-images.githubusercontent.com/113974143/236194932-8d9b43a9-85ad-4a32-957c-f5096e0fc979.png">

**Comment by MonsifFakhir** [comment]
- Faire une boucle avec un expert SEO, ajout d'un robot xt, index fichier - Ajouter un fichier robot txt permet d'ajouter (header dans
DSFR, cookies, 
-Coder une date de mise à jour : 
- Bing
