### ISSUE TITLE
Page d'accueil 

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#36]
**URL concernée :**  https://mda-preprod.dev.fabrique.social.gouv.fr/

**J'observe ce qui ne va pas :**  
1/ Il manque un pavé de texte dans le 1er layer (qu'est ce que l'autisme)
2/ Il manque les pictos dans le 2e layer (boite à outils)
3/ Je souhaite revoir les fiches pratiques les plus lues affichées à ce jour
4/ Il manque des photos illustratives dans le 1er et le dernier layer (qu'est ce que l'autisme et maison physique)
5/ Je souhaite reformuler le texte de la rubrique "Mon parcours"
6/ Je souhaite reformuler le texte de la rubrique "Mes aides"

**Je demande ce que je souhaiterais :**  

- [x]  1/ Corriger le bouton "Comprendre l'autisme" et utiliser le chapô validé : L’autisme est un trouble du neurodéveloppement (TND) précoce qui impacte les capacités de communication, les interactions sociales et les comportements des personnes. Ce trouble va souvent de pair avec d’autres manifestations : hyper ou hypo sensibilité aux sons, lumières, odeurs... , trouble du déficit de l’attention avec ou sans hyperactivité (TDA/H), troubles “dys” (dyslexie, dyspraxie, dysphasie,...). 

Lien strapi ==> qu-est-ce-que-l-autisme

- [x] 2/ Utiliser les pictos utilisés dans la maquette Figma

- [x] 3/ Remplacer les fiches les plus lues affichées par la liste ci-après : Qu'est ce que l'autisme ? > Plateforme de Coordination et d'Orientation > Parcours de diagnostic > Dossier MDPH > Acteurs et organismes > Groupes d'entraides

Liens strapi 
==> qu-est-ce-que-l-autisme
==> plateforme-coordination-et-d-orientation
==> parcours-de-diagnostic
==> dossier-mdph
==> acteurs-et-organismes
==> je-cherche-des-groupes-d-entraide

- [x] 4/ Utiliser les photos en PJ à ce ticket pour le layer 1 et dernier layer 

- [x] 5/ Remplacer le descriptif de la rubrique "Mon parcours" dans le layer "Démarches et outils" : En tant que personne autiste, parent ou aidant, plusieurs étapes clés sont à réaliser pour mener sa vie de la manière la plus autonome possible.

- [x] 6/ Remplacer le descriptif de la rubrique "Mes aides" dans le layer "Démarches et outils" : Selon votre situation, celle de enfant ou de votre proche, des ressources sont disponibles pour vous aider au quotidien.

Nota bene : une fois toutes les pages créées, je retesterai les liens cliquables pour m'assurer de leur bonne redirection.

![Immeuble_maison_autisme_facade](https://user-images.githubusercontent.com/113974143/214271169-357e8e35-e5f0-4361-b46b-ca82fec81996.png)
![shutterstock_1698087613](https://user-images.githubusercontent.com/113974143/214271179-0ac5bcce-485d-4bbf-82aa-98e11712e5e3.jpg)

**Comment by LauraAMIRIFabrique** [comment]
Tout est OK sur cette page sauf :

1/ 1er layer : Le lien de redirection quand on clique sur le bouton "Comprendre l'autisme" renvoie vers le contenu en préprod. Attention c'est bien le contenu en prod qui est à prendre. Slug strapi : qu-est-ce-que-l-autisme

2/ 2e layer Rubrique démarche et outils : 
- Lien cliquable vers Mes aides => KO (pas de lien en préprod, tu peux éventuellement utiliser le lien en prod strapi ; slug : mes-aides)
- Lien cliquable vers Mon diagnostic => KO : https://mda-preprod.dev.fabrique.social.gouv.fr/mon-diagnostic

3/ 3e layer - fiches pratiques les plus lues : 
Le lien de redirection quand on clique sur la fiche pratique "qu'est ce que l'autisme" renvoie vers le contenu en préprod. Attention c'est bien le contenu en prod qui est à prendre. Slug strapi : qu-est-ce-que-l-autisme

**Comment by sutter** [comment]
Les urls de ce ticket sont à vérifié en prod avec les liens des tuiles de la préprod :D
