### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#37]
**URL concernée :**  https://mda-preprod.dev.fabrique.social.gouv.fr/

**J'observe ce qui ne va pas :**  
1/ Quelques coquilles figurent dans le texte du footer
2/ Il manque le lien hypertexte "Plan du site"
3/ Il manque la mention du statut du RGAA 
4/ Les pages CGU, Mentions Légales et Politiques de confidentialités ne sont pas à jour ==> viendra dans un deuxième temps, je vois Osiris le 24/01 à 16h30.

**Je demande ce que je souhaiterais :**  

- [x]  1/ Texte du footer à remplacer :

Ce site est une version beta en cours de déploiement progressif. Il sera enrichi au fur et à mesure des retours des personnes concernées. Un oubli ? Une suggestion ? Utilisez le module [Je donne mon avis](https://mda-preprod.dev.fabrique.social.gouv.fr/je-donne-mon-avis) pour soumettre vos idées afin de contribuer à enrichir ce service public construit par et pour les personnes autistes et leurs proches. 

Attention, les demandes personnelles transmises via ce formulaire ne pourront être traités sur ce site, veuillez vous rapprocher de l'organisme en charge de votre dossier. Pour toute question, vous pouvez contacter [Autisme Info Services.](https://www.autismeinfoservice.fr/)

- [x]  3/ Afficher dans les liens hypertextes tout en bas du footer, avant CGU, le statut RGAA : 

Accessibilité : non conforme
Au clic ou au hover avec la souris, une pop in s'affiche pour indiquer le message suivant : Un audit d'accessibilité est prévu dans les prochaines semaines et permettra d'afficher un statut d'accessibilité certifié par l'organisme auditeur.

**Comment by sutter** [comment]
@LauraAMIRIFabrique Pour le point 3 je vais ajouter directement une page, cela sera plus rapide et de plus nous en auront besoin par la suite.

**Comment by LauraAMIRIFabrique** [comment]
Point 1, désolée, nouvelle MAJ : 

1/ Texte du footer à remplacer :
Ce site est fait pour les personnes autistes, par des personnes autistes, et avec des personnes concernées. C'est une version beta en cours de déploiement progressif. Vos commentaires, réactions et propositions sont précieux pour nous aider à améliorer ce service au fur et à mesure. Un oubli ? Une suggestion ? Utilisez le module [Je donne mon avis](https://mda-preprod.dev.fabrique.social.gouv.fr/je-donne-mon-avis) pour soumettre vos idées afin de contribuer à enrichir ce service public.

Attention, les demandes personnelles transmises via ce formulaire ne pourront être traitées sur ce site. Pour les demandes personnelles, veuillez vous rapprocher de l'organisme en charge de votre dossier. Pour toute question, vous pouvez contacter [Autisme Info Services.](https://www.autismeinfoservice.fr/)

**Comment by LauraAMIRIFabrique** [comment]
Merci - Désolée j'ai fait une erreur sur le texte du footer.
La dernière phrase c'est "Pour toute question, vous pouvez contacter [Autisme Info Service.](https://www.autismeinfoservice.fr/)"

Sans s à services ... désolée
