### ISSUE TITLE
Page plan du site

### ISSUE THREAD

**Issue by sutter** [SocialGouv/mda#40]
- [ ] Création du gabarit de page
- [ ] Branchement aux éléments de navigation
- [ ] Ajout du contenu
- [ ]  afficher dans les liens hypertextes tout en bas du footer, en toute première position : Plan du site

**Comment by sutter** [comment]
Pour le moment j'attends que le contenus soit ajouté afin de tester une génération automatique de cette page. Si j'ai un soucis avec la génération automatique je passerais la page en dur dans un premier temps.

**Comment by LauraAMIRIFabrique** [comment]
Nécessaire pour l'audit RG2A => cet item devient prioritaire

**Comment by sutter** [comment]
Url de review https://mda-preprod.dev.fabrique.social.gouv.fr/

**Comment by LauraAMIRIFabrique** [comment]
Merci, je pousse à mon contact RG2A et je vois si ça lui convient avant qu'on pousse en MEP
