### ISSUE TITLE
Mon parcours - Page Parent ou aidant

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#42]
**URL concernée :** https://mda-preprod.dev.fabrique.social.gouv.fr/mon-parcours/parent-personne-aidante

**J'observe ce qui ne va pas :**  
1/ Le titre est à modifier
2/ Le chapô est à modifier
3/ Les grandes étapes ne sont pas complètes et leur descriptif est à modifier
4/ Etape 6 - Les étapes de la vie du parcours parent sont à modifier
5/ Les liens de redirection sont à ajouter

**Je demande ce que je souhaiterais :**  

- [x] 1/ Pour cette page là, renommer le titre en "Mon parcours de parent ou d'aidant" 

- [x] 2/ Le chapô est le suivant : En tant que parent ou proche aidant, plusieurs étapes clés sont à réaliser pour accompagner votre proche à mener sa vie de la manière la plus autonome possible. Quelque soit votre situation, retrouvez ci-dessous des contenus et outils de guidance pour vous aider à y voir plus clair sur le déroulé de ces grandes étapes.

- [x] 3/ Les grandes étapes sont à compléter, dans l'ordre déjà validé sur les maquettes figma.

Les descriptifs de ces grandes étapes sont à modifier comme tel : 
a) Je me pose des questions : Je m'interroge sur les comportements de mon enfant ou de mon proche. 
Je souhaite repérer des signes de comportements ou de ressentis qui pourraient relever d'un trouble du neurodéveloppement comme l'autisme. 
Lien Strapi ==> je-m-interroge-sur-mon-enfant

b) Je démarre un diagnostic : J'accompagne mon enfant ou mon proche auprès d'un professionnel de santé et selon son avis médical le parcours de diagnostic peut démarrer.
Lien Strapi : parcours-de-diagnostic

c) Je prends connaissance de mes aides ==> Mon enfant ou mon proche peut bénéficier d’aides financières, matérielles et humaines, même s'ils n'ont pas encore de diagnostic. 
Lien Strapi : mes-aides

d) [le titre est également à modifier] Je sollicite la MDPH et je dépose un dossier : Lorsque mon enfant ou mon proche a finalisé son parcours de diagnostic et qu'il conclut à un TSA, je m'adresse à la Maison Départementale des Personnes Handicapées et je dépose un dossier. 
Lien strapi : je-sollicite-la-mdph-et-je-monte-un-dossier

e) Je prends connaissance des nouvelles aides ==> Lorsque mon enfant ou mon proche ont reçu une réponse de la Maison Départementale des Personnes Handicapées suite au dépôt de leur dossier, ils peuvent bénéficier de nouvelles aides. 
Lien Strapi : mes-aides

f) [le titre est également à modifier] J'accompagne mon enfant ou mon proche tout au long de sa vie : Plusieurs étapes clés sont à réaliser pour mener sa vie de la manière la plus autonome possible.

- [x] 4/ Etape 6 - Les étapes de la vie sont les suivantes : 

a) Etre scolarisé 

b) Etudier 
Lien strapi ==> etudier-du-college-aux-etudes-superieures

c) Travailler 
Lien Strapi ==> personne-tsa-travailler

c bis) Travailler quand on est parent ou aidant ==> griser le lien. Indiquer au hover ou avec une pop-up l'information suivante : Cette page est en cours de rédaction et sera prochainement disponible.

c) Se soigner
Lien Strapi ==>se-soigner

e) Se déplacer
Lien Strapi ==> se-deplacer

f) Se loger
Lien Strapi ==>se-loger

g) Partir en vacances,
Lien Strapi ==>partir-en-vacances

g bis) Avoir des loisirs
Lien Strapi ==>avoir-des-loisirs

h) Tisser du lien amical, amoureux et familial
Lien strapi ==> tisser-du-lien-amical-amoureux-et-familial

h) Etre protégé
Lien strapi ==> etre-protege

- [ ] 5/ Les liens seront à ajouter lorsque les pages auront été créées dans Strapi.
==> cf liens strapi fournis ci-dessus

**Comment by sutter** [comment]
Je vois que le lien "Être scolarisé" n'a pas de page. Je supprime l'entrée ou c'est juste un oubli ?

**Comment by LauraAMIRIFabrique** [comment]
Oui on a tjs pas reçu le texte … 
Tu peux le laisser en grisé pour le moment ?
Comme tu as fait pour la rubrique "Emploi du parent"

**Comment by LauraAMIRIFabrique** [comment]
Je sais que ce ticket n'était pas en review mais du coup j'anticipe car cette page est parfois différente de la page Personne autiste. Voici les éléments à traiter pour cette page là en particulier : 

- Mettre à jour le Chapô par : 
En tant que parent ou proche aidant, plusieurs étapes clés sont à réaliser pour accompagner votre enfant ou votre proche à mener sa vie de la manière la plus autonome possible. Quelque soit votre situation, retrouvez ci-dessous des contenus et outils de guidance pour vous aider à y voir plus clair sur le déroulé de ces grandes étapes.

- Etape 4 - Je sollicite la MDPH - mettre à jour le descriptif : Lorsque mon enfant ou mon proche a finalisé son parcours de diagnostic et qu'il conclut à des Troubles du Spectre de l'Autisme, je m'adresse à la Maison Départementale des Personnes Handicapées et je dépose un dossier.

- Etre scolarisé :  on a tjs pas reçu le texte … Tu peux le laisser en grisé pour le moment ?
Comme tu as fait pour la rubrique "Emploi du parent"

- Supprimer la ligne "vérifié le xxx par xxx"

- Liens cliquables sont tous KO sauf pour Je donne mon Avis et Annuaire.
Pour les 4 rubriques en bas de la page, remplacer les textes suivants :
1/ J'en parle autour de moi :
a) Remplacer par le titre : Je demande de l'aide à mon entourage
b) Remplacer le descriptif : Demander de l'aide à son entourage est un réflexe important pour améliorer sa qualité de vie en tant que parent, et faire face aux nombreux défis auxquels on se trouve confronté après le diagnostic de son enfant.
c) Rediriger vers la fiche : je-demande-de-l-aide-a-mon-entourage

2/ Je cherche des groupes avec qui échanger :
Mettre à jour la description : Échanger avec des personnes permet de trouver du soutien, de rompre avec l’isolement, de mieux comprendre la situation et de rechercher des solutions, mais également de valoriser votre expérience.
Rediriger vers la fiche : je-cherche-des-groupes-d-entraide

3/ Je donne mon avis :
Mettre à jour la description : Un oubli ? Une suggestion ? Utilisez le module Je donne mon avis pour soumettre vos idées afin de contribuer à enrichir ce service public.

4/ Annuaire :
Mettre à jour la description : Vous cherchez des contacts de confiance ? Un établissement ou un organisme ? Des professionnels de santé ? Une association ?

**Comment by LauraAMIRIFabrique** [comment]
Il y a eu 3 oublis dans mon ticket précédent : 

1/ Mettre à jour le Chapô par :
En tant que parent ou proche aidant, plusieurs étapes clés sont à réaliser pour accompagner votre enfant ou votre proche à mener sa vie de la manière la plus autonome possible. Quelque soit votre situation, retrouvez ci-dessous des contenus et outils de guidance pour vous aider à y voir plus clair sur le déroulé de ces grandes étapes.


2/ Etape 4 - Je sollicite la MDPH - mettre à jour le descriptif : Lorsque mon enfant ou mon proche a finalisé son parcours de diagnostic et qu'il conclut à des Troubles du Spectre de l'Autisme, je m'adresse à la Maison Départementale des Personnes Handicapées et je dépose un dossier.


3/ Pour le parcours parent aidant (uniquement, pas pour les personnes autistes ou pour les pros), il ne fallait pas écraser la rubrique 1 en bas à gauche. Tu peux remettre à la place : 
a) Remplacer par le titre : Je demande de l'aide à mon entourage
b) Remplacer le descriptif : Demander de l'aide à son entourage est un réflexe important pour améliorer sa qualité de vie en tant que parent, et faire face aux nombreux défis auxquels on se trouve confronté après le diagnostic de son enfant.
c) Rediriger vers la fiche : je-demande-de-l-aide-a-mon-entourage
