### ISSUE TITLE
Mon parcours - Page Professionnel de santé ou du médico-social

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#44]
URL concernée : Pas d'URL, c'est une page parcours à créer pour le personae Professionnel de santé ou du médico-social

J'observe ce qui ne va pas :
La page est à créer

Je demande ce que je souhaiterais : 

- [x] - Le titre est : Mon parcours de professionnel de santé ou du médico-social

- [x] - Le chapô est le suivant : Cette rubrique du site internet est en cours de construction pour le moment. Si vous êtes un professionnel de santé ou du médico-social, partagez-nous vos attentes en donnant votre avis via le formulaire "Je donne mon avis".

- [x] - Afficher les rubriques carrées suivantes : 

a) Comment diagnostiquer un patient potentiellement autiste 
Lien strapi ==> comment-diagnostiquer-un-patient-potentiellement-autiste

b) Parcours de diagnostic ==> lien strapi : parcours-de-diagnostic
c) Je donne mon avis ==> https://mda-preprod.dev.fabrique.social.gouv.fr/je-donne-mon-avis
d) Recommandations de Bonnes Pratiques Professionnelles ==> lien strapi : recommandations-de-bonnes-pratiques-professionnelles

- [x] - Nota bene : Les liens seront à ajouter lorsque les pages auront été créées dans Strapi.

**Comment by LauraAMIRIFabrique** [comment]
- Coquille dans le titre : médico-social sans e à social
- Supprimer la ligne "vérifié le xxx par xxx"
- KO quand on clique sur les liens de redirection pour toutes les rubriques, sauf pour la page JDMA. On a un 404 not found : 

a) Comment diagnostiquer un patient potentiellement autiste
Lien strapi ==> comment-diagnostiquer-un-patient-potentiellement-autiste

b) Parcours de diagnostic ==> lien strapi : parcours-de-diagnostic

d) Recommandations de Bonnes Pratiques Professionnelles ==> lien strapi : recommandations-de-bonnes-pratiques-professionnelles

**Comment by sutter** [comment]
Hum, tu est sure pour tes liens car https://maisondelautisme.fabrique.social.gouv.fr/fiches-pratiques/comment-diagnostiquer-un-patient-potentiellement-autiste n'existe pas

**Comment by sutter** [comment]
Celui-ci est ok https://maisondelautisme.fabrique.social.gouv.fr/fiches-pratiques/comment-puis-je-diagnostiquer-un-patient-potentiellement-autiste

**Comment by sutter** [comment]
Il va vraiment falloir faire attention à ne pas faire trop bouger les slugs, sinon ça va vite être le bordel.

**Comment by sutter** [comment]
A mon sens les URL sont toutes ok

**Comment by LauraAMIRIFabrique** [comment]
> Hum, tu est sure pour tes liens car https://maisondelautisme.fabrique.social.gouv.fr/fiches-pratiques/comment-diagnostiquer-un-patient-potentiellement-autiste n'existe pas

oui excuse moi, je fatigue. Merci pour la correction que tu as trouvé par toi meme

**Comment by LauraAMIRIFabrique** [comment]
Je donne mon avis :
Mettre à jour la description : Un oubli ? Une suggestion ? Utilisez le module Je donne mon avis pour soumettre vos idées afin de contribuer à enrichir ce service public.
