### ISSUE TITLE
Page politique de confidentialité

### ISSUE THREAD

**Issue by sutter** [SocialGouv/mda#66]
- [x] Création du gabarit de page
- [x] Branchement aux élément de navigation
- [x] Intégrer le contenu en dur

**Comment by LauraAMIRIFabrique** [comment]
Remplacer l'adresse du site Autisme info service par l'email maisondelautisme@fabrique.social.gouv.fr

![Image](https://user-images.githubusercontent.com/113974143/215435909-04a64e69-666c-45aa-8a3a-f2fe02805e6a.png)
