### ISSUE TITLE
Aperçu des chapô sans mise en forme - mais avec des balises 

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#94]
**URL concernée :** https://maisondelautisme.fabrique.social.gouv.fr/fiches-pratiques

**J'observe ce qui ne va pas :**  
L'aperçu des chapô ne prend pas en compte les balises de mise en forme qui sont dans les pages de fiche pratique et laisse apparaitre les balises. Exemple en screenshot.

**Je demande ce que je souhaiterais :**  
Ne pas faire apparaitre les balises en texte ; ni faire apparaitre la mise en forme (le gras ou la mise en forme URL par exemple). Juste faire apparaitre le texte.

![image](https://user-images.githubusercontent.com/113974143/216003695-f8035ebd-5fe0-41d2-b93c-11008c4ed377.png)

**Comment by lsagetlethias** [comment]
https://github.com/pchiwan/markdown-truncate/blob/main/src/index.js

**Comment by sutter** [comment]
Il faut rajouter un champ récapitulatif en format texte dur sur les fiches pratiques, car certains contenus de tuile contiennent des URL.
Ce qui n'est pas souhaitable car cela produit une erreur de composant.
Je ne peux pas avoir 2 URL par tuile.

**Comment by LauraAMIRIFabrique** [comment]
Merci Laurent pour cette précision
Sur Strapi en préprod, je ne vois pas de champs récapitulatif dédié où je pourrais mettre le chapô ; peux-tu me préciser s'il s'agit de ce nouveau champ en bas à droite "excerpt" ? 


![Image](https://user-images.githubusercontent.com/113974143/224771825-0ba30df1-e421-4cc0-a409-013792ca13b0.png)

Attention par ailleurs, j'ai l'impression que la modification passée contient un bug, cf chapô toujours présent https://mda-preprod.dev.fabrique.social.gouv.fr/fiches-pratiques



![Image](https://user-images.githubusercontent.com/113974143/224772100-783c956a-1114-4d22-bf42-e8e11c32d0bc.png)

**Comment by LauraAMIRIFabrique** [comment]
Ok tout est bon on cloture le ticket
