### ISSUE TITLE
Ajout des logos & liens vers les réseaux sociaux MDA

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#97]
**URL concernée :** toutes les pages https://maisondelautisme.fabrique.social.gouv.fr/

**J'observe ce qui ne va pas :**  
Il serait important d'avoir les accès aux réseaux sociaux de la maison de l'autisme depuis le site 

**Je demande ce que je souhaiterais :**  
Ajouter les logos & liens vers les réseaux sociaux sur le site
- Instagram : https://www.instagram.com/lamaisondelautisme/ 
- Facebook : https://www.facebook.com/maisondelautisme 
- LinkedIn : https://www.linkedin.com/company/maisondelautisme

**Comment by sutter** [comment]
Url de recette [https://mda-feat-post-launch-fixs-21mldg0r.dev.fabrique.social.gouv.fr](https://mda-feat-post-launch-fixs-21mldg0r.dev.fabrique.social.gouv.fr)
