### ISSUE TITLE
Message d'accusé réception après l'envoi de formulaire 

### ISSUE THREAD

**Issue by LauraAMIRIFabrique** [SocialGouv/mda#98]
**URL concernée :** https://maisondelautisme.fabrique.social.gouv.fr/je-donne-mon-avis

**J'observe ce qui ne va pas :**  
Les usagers ne savent pas si leur feedback a été envoyé une fois qu'ils ont cliqué sur "envoyer"

**Je demande ce que je souhaiterais :**  
Afficher un message persistant (pas un toaster) sur un aplat vert (si OK avec le DSFR) qui dit "Merci pour votre participation ! Nous avons bien reçu votre message. Nous allons en prendre connaissance pour voir comment améliorer le site. "

**Comment by sutter** [comment]
Url de recette [https://mda-feat-post-launch-fixs-21mldg0r.dev.fabrique.social.gouv.fr](https://mda-feat-post-launch-fixs-21mldg0r.dev.fabrique.social.gouv.fr)
